### ISSUE TITLE
Plots missing

### ISSUE THREAD

**Issue by BasvanH** [guydavis/machinaris#170]
**Describe the bug**
I have a farm and one of the nodes is acting strange. A harvester+plotter create new plots, they are in the directory, with **chia plots check** they can be found and are valid, but on the full node they are not vissable. New onse after a few days ago are not vissable.

**To Reproduce**
Dont know.

**Expected behavior**
New plots of farm plotter should be visable in machinaris.

**System setup:**
 - Ubuntu 20.14
 - Docker version: 20.10.2
 - Machinaris branch: main
 - Machinaris version number: 0.50

**Comment by guydavis** [comment]
Good day, please take a look at your [logs](https://github.com/guydavis/machinaris/wiki/Troubleshooting#nothing-works--where-are-the-logs), particularly ~/.machinaris/machinaris/logs/apisrv.log.  

Also, verify your `[plots_dir](https://github.com/guydavis/machinaris/wiki/FAQ#can-i-use-two-or-more-final-destination-directories-to-hold-my-plots)` variable is set correctly on all your systems.

**Comment by BasvanH** [comment]
Hi!

The plots directory of the plotter+harvester is set fine, all the plots are discovered with "chia plots check". It's also checked in at the full-node, no network issues.

I see a lot of messages in the apisrv.log:
```
[2021-07-12 06:03:01 +0000] [75] [INFO] Failed to load recent challenges and send.
[2021-07-12 06:03:01 +0000] [75] [INFO] Traceback (most recent call last):
  File "/machinaris/api/schedules/status_challenges.py", line 29, in update
    for challenge in recent_challenges.rows:
AttributeError: 'list' object has no attribute 'rows'
```

**Comment by BasvanH** [comment]
That log snippet was from the plotter+harvester.

This is what's in the apisrv.log of the fullnode:
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/views.py", line 83, in view
    return self.dispatch_request(*args, **kwargs)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/views.py", line 157, in dispatch_request
    return meth(*args, **kwargs)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask_smorest/etag.py", line 85, in wrapper
    resp = func(*args, **kwargs)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/webargs/core.py", line 450, in wrapper
    return func(*args, **kwargs)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask_smorest/arguments.py", line 77, in wrapper
    return func(*f_args, **f_kwargs)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask_smorest/response.py", line 73, in wrapper
    func(*args, **kwargs))
  File "/machinaris/api/views/farms/resources.py", line 35, in post
    item = Farm.query.get(new_item['hostname'])
  File "<string>", line 2, in get
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 942, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 946, in _get_impl
    return self.session._get_impl(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2839, in _get_impl
    return db_load_fn(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 531, in load_on_pk_identity
    session.execute(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3165, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3244, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3214, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2068, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3211, in _wrap_pool_connect
    return fn()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
    return _ConnectionRecord(self)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 368, in __init__
    self.__connect()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 622, in __connect
    pool.dispatch.connect.for_modify(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 335, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 341, in __call__
    fn(*args, **kw)
  File "/machinaris/api/__init__.py", line 16, in set_sqlite_pragma
    cursor.execute("PRAGMA journal_mode=WAL")
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) disk I/O error
(Background on this error at: http://sqlalche.me/e/14/e3q8)
```

**Comment by BasvanH** [comment]
I did a restart of the full node, now the disk I/O errors are gone and there's one error remaining:

```
[2021-07-12 06:32:18 +0000] [2693] [ERROR] Exception on /plots/ [POST]
Traceback (most recent call last):
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1750, in _execute_context
    self.dialect.do_executemany(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 714, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: plots.plot_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/views.py", line 83, in view
    return self.dispatch_request(*args, **kwargs)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/views.py", line 157, in dispatch_request
    return meth(*args, **kwargs)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask_smorest/etag.py", line 85, in wrapper
    resp = func(*args, **kwargs)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/webargs/core.py", line 450, in wrapper
    return func(*args, **kwargs)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask_smorest/arguments.py", line 77, in wrapper
    return func(*f_args, **f_kwargs)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask_smorest/response.py", line 73, in wrapper
    func(*args, **kwargs))
  File "/machinaris/api/views/plots/resources.py", line 43, in post
    db.session.commit()
  File "<string>", line 2, in commit
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3298, in flush
    self._flush(objects)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3438, in _flush
    transaction.rollback(_capture_exception=True)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3398, in _flush
    flush_context.execute()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 242, in save_obj
    _emit_insert_statements(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1094, in _emit_insert_statements
    c = connection._execute_20(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1750, in _execute_context
    self.dialect.do_executemany(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 714, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: plots.plot_id
[SQL: INSERT INTO plots (plot_id, hostname, dir, file, size, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: (('3b02ef5a', '192.168.28.201', '/plots', 'plot-k32-2021-07-10-23-04-3b02ef5ac976a19fac8ed61313265f3ffc6de1001ed4b5c801a3f48fe712b76c.plot', 108795518501, '2021-07-11 14:39:56', None), ('c064d26c', '192.168.28.201', '/plots', 'plot-k32-2021-07-10-07-23-c064d26c29b794518c9bb037d49a4d64e5bcb100c53582e9e35debab94747322.plot', 108822615982, '2021-07-10 23:04:06', None), ('6558686e', '192.168.28.201', '/plots', 'plot-k32-2021-07-09-15-00-6558686ee90064f832680af59be0f3b88d4f6cbcb613885a2aa7cfb4738019cc.plot', 108897633910, '2021-07-10 05:57:49', None), ('2dc3caf1', '192.168.28.201', '/plots', 'plot-k32-2021-07-07-07-49-2dc3caf1f6378e47fc7b69c588fb88ae43b89a7d9b3d2e3c7b04ab5b5a04262f.plot', 108815154803, '2021-07-10 02:50:31', None), ('f68a61e2', '192.168.28.201', '/plots', 'plot-k32-2021-07-06-18-59-f68a61e26b6dcaf179341f8f39f809f2147b0806886a08e1187aba77f0d7d62f.plot', 108839037262, '2021-07-10 00:03:04', None), ('1debf9c1', '192.168.28.201', '/plots', 'plot-k32-2021-07-06-06-15-1debf9c18bb690855f96c6d4894039302ce6413a61bc3892e6fa34331c9e2dfa.plot', 108794452103, '2021-07-09 03:25:38', None), ('7b0c6b19', '192.168.28.201', '/plots', 'plot-k32-2021-07-05-17-27-7b0c6b19e1bf09454deb00092d32715822a1de6adab3aaf75abe1e1873d34659.plot', 108829802721, '2021-07-09 00:46:59', None), ('d3271e5a', '192.168.28.201', '/plots', 'plot-k32-2021-07-05-04-37-d3271e5ab3ffcfba39ccd8d7705ca56d3b03ec4171f486f3305930564362e0f9.plot', 108823725170, '2021-07-08 22:05:27', None), ('b1e02c08', '192.168.28.201', '/plots', 'plot-k32-2021-07-04-12-47-b1e02c082622b24459e4f1e4be062f71ee08362e8b5b848fccb2b8ba8a8e5e44.plot', 108841535968, '2021-07-08 18:27:24', None))]
(Background on this error at: http://sqlalche.me/e/14/gkpj)
[2021-07-12 06:32:53 +0000] [2480] [INFO] Failed to load farm summary and send.
[2021-07-12 06:32:53 +0000] [2480] [INFO] Traceback (most recent call last):
  File "/machinaris/api/schedules/status_farm.py", line 28, in update
    "plot_count": farm_summary.plot_count,
AttributeError: 'FarmSummary' object has no attribute 'plot_count'
```

**Comment by BasvanH** [comment]
```
root@xxxxxxx:/chia-blockchain# chia farm summary
Farming status: Farming
Total chia farmed: 0.0
User transaction fees: 0.0
Block rewards: 0.0
Last height farmed: 0
Remote Harvester for IP: xxxxxxx
   15 plots of size: 1.485 TiB
Remote Harvester for IP: xxxxxxxxxxxx
   19 plots of size: 1.881 TiB
Remote Harvester for IP: xxxxxxxxxxxxxx
   0 plots of size: 0.000 MiB
Remote Harvester for IP: xxxxxxxxxxxxxx
   19 plots of size: 1.881 TiB
Remote Harvester for IP: xxxxxxxxxxxx
   19 plots of size: 1.881 TiB
Remote Harvester for IP: xxxxxxxxxxxx
   9 plots of size: 912.193 GiB				<= 5 of those plots are not added to machinaris
Plot count for all harvesters: 81
Total size of plots: 8.018 TiB
Estimated network space: 32.022 EiB
Expected time to win: 2 years and 3 months
Note: log into your key using 'chia wallet show' to see rewards for each key
```

**Comment by BasvanH** [comment]
@guydavis, did you perhaps find the time to take a look at this?

**Comment by BasvanH** [comment]
I've managed to solve the SQL error, this was because of a duplicate plot id.

But still this error is there:
```
[2021-07-13 18:58:42 +0000] [1873] [INFO] Traceback (most recent call last):
  File "/machinaris/api/schedules/status_farm.py", line 28, in update
    "plot_count": farm_summary.plot_count,
AttributeError: 'FarmSummary' object has no attribute 'plot_count'
```

**Comment by guydavis** [comment]
Hi, yes!  Thanks for the `chia farm summary` output above.  There is a defect in v0.5.0 where Summary page status is not properly recorded/displayed if the fullnode has zero plots, only harvesters have plots.  Fix is incoming today for the [test version](https://github.com/guydavis/machinaris/wiki/Releases#release-streams).  Will update here as soon as it is ready.

**Comment by guydavis** [comment]
Ok, please pull [test version](https://github.com/guydavis/machinaris/wiki/Releases#release-streams) image.  

Please note, there is a [process for connecting](https://github.com/guydavis/machinaris/wiki/Workers#harvester) a Machinaris harvester/worker to the Machinaris fullnode/controller.  

There are more steps than just a plain Chia harvester, so you'll need to be running Machinaris on all systems for full-functionality.

**Comment by BasvanH** [comment]
Yes, I know. My machinaris/chia farm works great, thanks!

Bug has been fixed.
