### ISSUE TITLE
500 internal server error since 0.6.7

### ISSUE THREAD

**Issue by cmbcbe** [guydavis/machinaris#488]
**Describe the bug**
after several reinstallation (emptying docker and restart it), i get 500 internal server error after few hours of running

**To Reproduce**
don't know

Steps to reproduce the behavior, e.g.:
1. Set up config with '...'
2. Run other programs '....'
3. Run Machinaris with '....'

**Expected behavior**

**System setup:**
Debian 11
Docker 20.10.11
Machinaris main 0.6.7

**Additional context & screenshots**
here is the log in webui.log
2021-12-09 14:28:39 [63] [ERROR] Exception on /index [GET]
Traceback (most recent call last):
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
    cursor.execute(statement, parameters)
sqlite3.DatabaseError: database disk image is malformed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/machinaris/web/routes.py", line 35, in index
    chia.challenges_chart_data(farm_summary)
  File "/machinaris/web/actions/chia.py", line 111, in challenges_chart_data
    challenges = db.session.query(c.Challenge).filter(c.Challenge.blockchain==blockchain,
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2759, in all
    return self._iter().all()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2894, in _iter
    result = self.session.execute(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
    cursor.execute(statement, parameters)

Thank you.

Machinaris is behind traefik on SSL, working for a while since now...

**Comment by guydavis** [comment]
Sorry for the trouble.  Please [reset the status database](https://github.com/guydavis/machinaris/wiki/Troubleshooting#reset-machinaris-database).

**Comment by cmbcbe** [comment]
Hello,
this procedure fix temporaly the issue, but it happen again somes minutes after (~30min)
Thank you

**Comment by guydavis** [comment]
Hi, sorry again.  I have refactored the entire database layer to isolate down to per-table locks, rather than a single database lock.  While this never was an issue for smaller farms, those with many workers and many plots encountered these database issues more often.  For those large farms, I have updated this behavior in the [current `:develop` images](https://github.com/guydavis/machinaris/wiki/Releases).  Feel free to try the early changes there, or alternatively wait until the changes land in the `:test` images.  All feedback is appreciated.

**Comment by guydavis** [comment]
Any update on this against the `:test` images?  Still encountering this problem?

**Comment by guydavis** [comment]
Alright, I'm marking this as fixed in upcoming release.

**Comment by guydavis** [comment]
Marking as fixed in [v0.6.8](https://github.com/guydavis/machinaris/releases/tag/0.6.8).  Thanks again!
