### ISSUE TITLE
error with sync maybe :(

### ISSUE THREAD

**Issue by panayotovip** [guydavis/machinaris#546]
**Describe the bug**
do not sync node. error is cli:
```
root@machinaris-chia:/chia-blockchain# chia show -s
Exception from 'show' Traceback (most recent call last):
  File "/chia-blockchain/chia/cmds/show.py", line 41, in show_async
    blockchain_state = await client.get_blockchain_state()
  File "/chia-blockchain/chia/rpc/full_node_rpc_client.py", line 27, in get_blockchain_state
    response = await self.fetch("get_blockchain_state", {})
  File "/chia-blockchain/chia/rpc/rpc_client.py", line 49, in fetch
    raise ValueError(res_json)
ValueError: {'error': "b'\\xd7\\x80\\xd2,z\\x87\\xc9\\xe0\\x1d\\x98\\xb4\\x9a\\t\\x10\\xf6p\\x1c;\\x95\\x01WA1k?\\xda\\x04.]{\\x81\\xd2'", 'success': False}
```

**To Reproduce**
i try to setup new container, copy only mnenonic file

**Expected behavior**
normal work.

**System setup:**
 - OS: Debian GNU/Linux 10 (buster)
 - Docker version : 20.10.12
 - Machinaris branch: main
 - Machinaris version number : 0.6.8

**Config**
```
docker run \
-d -t --name machinaris-chia \
-h machinaris-chia \
-v "/srv/dev-disk-by-uuid-0ff56b53-6de2-43cb-bb56-0c6c1d402c3c/chia-plots2:/plots/disk2" \
-v "/srv/dev-disk-by-uuid-a0a7c2ca-236a-4ff6-acd5-c8dbdfaf37db/chia-plots1:/plots/disk1" \
-v "/srv/dev-disk-by-uuid-1b06cc69-5041-4a4b-bcf4-2e3c4b242668/chia-plotting:/plotting" \
-v "/srv/dev-disk-by-uuid-1b06cc69-5041-4a4b-bcf4-2e3c4b242668/machiinaris/chia:/root/.chia" \
-e TZ=Europe/Sofia \
-e mode=fullnode \
-e plots_dir=/plots/disk1:/plots/disk2 \
-e blockchains=chia \
-e worker_address=192.168.0.10 \
-p 8926:8926 -p 8927:8927 \
-p 8444:8444 -p 8447:8447 \
-p 6888:6888 -p 6885:6885 \
--net=local-network\
--ip=192.168.0.10 \
--restart unless-stopped \
ghcr.io/guydavis/machinaris:latest
```

**Additional context & screenshots**
screenshot => https://ibb.co/X5Jkfhb

**Comment by guydavis** [comment]
First off, let me thank you for providing such a detailed error report.  This is quite rare and I really appreciate it.

Unfortunately however, judging by the error provided, this looks to be corruption of your local Chia blockchain database which many have encountered.  I would recommend you perform a [reset of the database](https://github.com/guydavis/machinaris/wiki/Troubleshooting#reset-chia-configwalletblockchain).
