### ISSUE TITLE
WebUI does not load.

### ISSUE THREAD

**Issue by saboluigi** [guydavis/machinaris#551]
After updating to 0.6.8 I initially received an internal server error and now the page does not load at all.

Steps to reproduce the behavior, e.g.:
I have all forks running on Unraid and they all worked before.

**Expected behavior**
I expected the webui to load as normal as it did before.

**System setup:**
 - OS: Unraid 6.9.2
 - 20.10.5
 - Machinaris branch: main
 - 0.6.8

**Config**
The config is set up with the array as plot storage and a single SSD drive as plotter storage.

I run full node with plotting.

```
I installed from Community Apps
```

</details>

**Additional context & screenshots**
2022-01-24 10:48:00 [52] [INFO] Listening at: http://0.0.0.0:8926 (52)
2022-01-24 10:48:00 [52] [INFO] Listening at: http://0.0.0.0:8926 (52)
2022-01-24 10:48:00 [52] [INFO] Using worker: sync
2022-01-24 10:48:00 [52] [INFO] Using worker: sync
2022-01-24 10:48:00 [63] [INFO] Booting worker with pid: 63
2022-01-24 10:48:00 [63] [INFO] Booting worker with pid: 63
2022-01-24 10:48:00 [64] [INFO] Booting worker with pid: 64
2022-01-24 10:48:00 [64] [INFO] Booting worker with pid: 64
2022-01-24 10:48:06 [64] [INFO] 192.168.1.50 - - [24/Jan/2022:10:48:06 -0500] "GET / HTTP/1.1" 200 1160 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
2022-01-24 10:48:06 [64] [INFO] 192.168.1.50 - - [24/Jan/2022:10:48:06 -0500] "GET /static/landing.gif HTTP/1.1" 200 0 "http://192.168.1.12:8926/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
2022-01-24 10:48:06 [63] [INFO] 192.168.1.50 - - [24/Jan/2022:10:48:06 -0500] "GET /static/machinaris.png HTTP/1.1" 200 0 "http://192.168.1.12:8926/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
2022-01-24 10:48:06 [64] [INFO] 192.168.1.50 - - [24/Jan/2022:10:48:06 -0500] "GET /static/favicon.ico HTTP/1.1" 200 0 "http://192.168.1.12:8926/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
2022-01-24 10:48:06 [63] [INFO] 192.168.1.50 - - [24/Jan/2022:10:48:06 -0500] "GET /static/favicon.ico HTTP/1.1" 304 0 "http://192.168.1.12:8926/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
2022-01-24 10:48:09 [64] [ERROR] Exception on /index [GET]
Traceback (most recent call last):
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: workers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/machinaris/web/routes.py", line 33, in index
    workers = worker.load_worker_summary()
  File "/machinaris/web/actions/worker.py", line 46, in load_worker_summary
    wkrs = query.all()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2759, in all
    return self._iter().all()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2894, in _iter
    result = self.session.execute(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1692, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: workers
[SQL: SELECT workers.hostname AS workers_hostname, workers.port AS workers_port, workers.blockchain AS workers_blockchain, workers.displayname AS workers_displayname, workers.mode AS workers_mode, workers.services AS workers_services, workers.url AS workers_url, workers.config AS workers_config, workers.latest_ping_result AS workers_latest_ping_result, workers.ping_success_at>
FROM workers ORDER BY workers.displayname, workers.blockchain]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-01-24 10:48:09 [64] [ERROR] Exception on /index [GET]
Traceback (most recent call last):
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: workers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)

**Comment by guydavis** [comment]
Please 'Check for Updates' on the Unraid Docker UI page to ensure you have the latest images.  Then, [reset the Machinaris database](https://github.com/guydavis/machinaris/wiki/Troubleshooting#reset-machinaris-database) as this is indicative of a database corruption or migration issue.  A reset should help.
