### ISSUE TITLE
Locale error?

### ISSUE THREAD

**Issue by dualmacops** [guydavis/machinaris#673]
**Describe the bug**
`Internal Server Error The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.`

Only index, pools, and settings works.

**With develop tag instead of latest of the docker image everything works on every page.**
It also spits error on the docker logs, i think it works just becouse the image is in debug mode.

**System setup:**
 - OS: DSM 6.2.3-25426
 - Docker version number 20.10.3 -
 - Machinaris branch: main
 - Machinaris version number Machinaris 0.7.1

**Config**
<details><summary>full configuration</summary>

```
version: '3.7' 
services: 
    machinaris: 
        image: ghcr.io/guydavis/machinaris:latest 
        container_name: machinaris 
        hostname: xxx
        restart: always 
        volumes: 
            - ./machinaris:/root/.chia 
            - "./plots1:/plots1" 
            - "./plotting:/plotting" 
        environment: 
            - TZ=Europe/Madrid 
            - mode=fullnode 
            - worker_address=192.168.1.123 
            - plots_dir=/plots1 
            - blockchains=chia 
        ports: 
            - 8926:8926 
            - 8927:8927 
            - 8444:8444 
            - 8447:8447 
 
```

</details>

Webgui.log says:
```
2022-05-09 18:27:49 [85] [INFO] 192.168.160.1 - - [09/May/2022:18:27:49 +0200] "GET /summary HTTP/1.1" 500 290 "http://xxx:8926/index" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-09 18:27:49 [85] [INFO] 192.168.160.1 - - [09/May/2022:18:27:49 +0200] "GET /favicon.ico HTTP/1.1" 200 0 "http://xxx:8926/summary" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-09 18:27:49 [83] [INFO] INIT: Accept-Language: es-ES,es;q=0.9  ---->  matched locale: None
2022-05-09 18:27:49 [83] [INFO] INIT: Accept-Language: es-ES,es;q=0.9  ---->  matched locale: None
2022-05-09 18:27:49 [83] [INFO] ROUTES: Accept-Language: es-ES,es;q=0.9  ---->  matched locale: None
2022-05-09 18:27:49 [83] [INFO] ROUTES: Accept-Language: es-ES,es;q=0.9  ---->  matched locale: None
2022-05-09 18:27:49 [83] [ERROR] Exception on /summary [GET]
Traceback (most recent call last):
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/machinaris/web/routes.py", line 89, in summary
    return render_template('summary.html', reload_seconds=120, summaries=summaries, global_config=gc,
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/chia-blockchain/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/chia-blockchain/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/chia-blockchain/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/machinaris/web/templates/summary.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/machinaris/web/templates/base.html", line 202, in top-level template code
    {% block scripts %}{% endblock %}
  File "/machinaris/web/templates/summary.html", line 209, in block 'scripts'
    "url": "{{ url_for('static', filename='3rd_party/i18n/datatables.'+lang+'.json') }}"
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by dualmacops** [comment]
It's working with :test 
Now the log says:
```
2022-05-09 19:28:10 [89] [INFO] LOCALE: Accept-Language: es-ES,es;q=0.9 returned no match so defaulting to 'en'.
2022-05-09 19:28:10 [89] [INFO] LOCALE: Accept-Language: es-ES,es;q=0.9 returned no match so defaulting to 'en'.
```
Thanks for the fast response.

**Comment by guydavis** [comment]
Thanks very much for confirming the fix.  I hope to get the upcoming final release of Machinaris v0.7.2 out soon.  Please stick with `:test` image until then.  Thanks for the feedback and let me know if you have further questions.

**Comment by guydavis** [comment]
This fix is now available in the [Machinaris v0.7.2 release](https://github.com/guydavis/machinaris/releases/tag/0.7.2) today. Thanks!
