### ISSUE TITLE
pool page return ""

### ISSUE THREAD

**Issue by fisherwei** [guydavis/machinaris#923]
machinaris is running in docker.

image: ghcr.io/guydavis/machinaris:latest

Chia 2.0.0
Chiadog 0.7.5+dev
Machinaris 2.0.0
Plotman 0.5.3+dev

```
2023-09-04 23:01:52 [710551] [ERROR] Exception on /pools [GET]
Traceback (most recent call last):
  File "/chia-blockchain/venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/chia-blockchain/venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/chia-blockchain/venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/chia-blockchain/venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/machinaris/web/routes.py", line 604, in pools
    return render_template('pools.html', pools= p.load_pools(), global_config=gc, selected_blockchain = selected_blockchain)
  File "/machinaris/web/actions/pools.py", line 47, in load_pools
    return Pools(pools, plotnfts)
  File "/machinaris/web/models/pools.py", line 75, in __init__
    errors = self.extract_unique_errors(pool_state)
  File "/machinaris/web/models/pools.py", line 112, in extract_unique_errors
    if not error['error_message'] in errors:
TypeError: list indices must be integers or slices, not str
2023-09-04 23:01:52 [710551] [INFO] 10.1.64.139 - - [04/Sep/2023:23:01:52 +0800] "GET /pools HTTP/1.1" 500 265 "http://10.1.64.8:8926/wallet" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"

```

dump pool_state['pool_errors_24h'] from "/machinaris/web/models/pools.py", line 112

```
    "pool_errors_24h": [
        [
            1693758447,
            {
                "error_code": 16,
                "error_message": "Server disconnected"
            }
        ]
    ],
```

**Comment by guydavis** [comment]
Hi, a patch has already been made for this reporting error in Machinaris, to reflect the underlying Chia error.  Please try image: `machinaris:develop` in the [development stream](https://github.com/guydavis/machinaris/wiki/Releases#release-streams).

**Comment by fisherwei** [comment]
yes, it is fixed.
